In [1]:
import pandas as pd
import MetaTrader5 as mt5
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

In [2]:
# initialize MetaTrader 5
if mt5.initialize():
    print("Initialization successful")
else:
    print("Initialization unsuccessful")
    mt5.shutdown()

login = 6048029
password = 'yxzgltu0'
server = 'OANDA-OGM MT5 Demo'

mt5.login(login, password, server)

# login credentials

login = 6048029
password = 'yxzgltu0'
server = 'OANDA-OGM MT5 Demo'

credentials = mt5.login(login, password, server)

if credentials:
    accountInfo = mt5.account_info()
    if accountInfo is not None:
        account_info_dict = mt5.account_info()._asdict()
        df = pd.DataFrame(list(account_info_dict.items()), columns=['property', 'value'])
        print("account_info() as dataframe:")
        print(df)
else:
    print("Connection failed", mt5.last_error())

Initialization successful
account_info() as dataframe:
              property               value
0                login             6048029
1           trade_mode                   0
2             leverage                 100
3         limit_orders                   0
4       margin_so_mode                   0
5        trade_allowed                True
6         trade_expert                True
7          margin_mode                   2
8      currency_digits                   2
9           fifo_close               False
10             balance                98.6
11              credit                 0.0
12              profit                 0.0
13              equity                98.6
14              margin                 0.0
15         margin_free                98.6
16        margin_level                 0.0
17      margin_so_call               100.0
18        margin_so_so                50.0
19      margin_initial                 0.0
20  margin_maintenance                 0.0
21              assets                 0.0
22         liabilities                 0.0
23  commission_blocked                 0.0
24                name         yarnny lock
25              server  OANDA-OGM MT5 Demo
26            currency                 USD
27             company   OANDA Corporation

In [3]:
# Get the first 1000 bars, of the 1 HR time frame from EURUSD


rates = mt5.copy_rates_from_pos("EURUSD", mt5.TIMEFRAME_H1, 0, 1000)

# display each element of obtained data in a new line
#print("Display obtained data 'as is'")
#for rate in rates:
   # print(rate)

# create DataFrame out of the obtained data
df = pd.DataFrame(rates)
# convert time in seconds into the datetime format
df['time'] = pd.to_datetime(df['time'], unit='s')

# display data
print("\nDisplay dataframe with data")
print(df)

Display dataframe with data
                   time     open     high      low    close  tick_volume  \
0   2022-01-20 06:00:00  1.13530  1.13531  1.13479  1.13503         1430
1   2022-01-20 07:00:00  1.13503  1.13525  1.13449  1.13494         2252
2   2022-01-20 08:00:00  1.13494  1.13529  1.13470  1.13495         2100
3   2022-01-20 09:00:00  1.13496  1.13664  1.13480  1.13593         4634
4   2022-01-20 10:00:00  1.13593  1.13685  1.13519  1.13543         6492
..                  ...      ...      ...      ...      ...          ...
995 2022-03-18 17:00:00  1.10249  1.10434  1.10239  1.10294        11318
996 2022-03-18 18:00:00  1.10292  1.10533  1.10263  1.10475        12434
997 2022-03-18 19:00:00  1.10476  1.10717  1.10419  1.10602        10582
998 2022-03-18 20:00:00  1.10602  1.10637  1.10501  1.10581         5417
999 2022-03-18 21:00:00  1.10581  1.10586  1.10420  1.10467         2978

     spread  real_volume
0         0            0
1        10            0
2         0            0
3        10            0
4        10            0
..      ...          ...
995      10            0
996      10            0
997      10            0
998      10            0
999      10            0

[1000 rows x 8 columns]

In [4]:
# function for finding trend line up
# if the middle is higher than the first two bars and the last two bars, then it is a fractal
# else break

def uptrend(df1, n2, n1):
    for i in range(n2, n1 - 3):
        if df1.high[i] < df1.high[i + 1]:
            break
        if df1.high[i] < df1.high[i + 2]:
            break
        if df1.high[i] < df1.high[i - 1]:
            break
        if df1.high[i] < df1.high[i - 2]:
            break
        return True
    return False

In [5]:
# look for another fractal that is lower than the previous fractal that was found
# if the fractal has the same time as the first fractal break out the loop


def uptrend2(df2, n3, n4):
    for a in range(n3, n4 - 3):
        if df2.high[a] > frac1[0][1]:
            break
        if df2.time[a] == frac1[0][2]:
            break
        if df2.high[a] < df2.high[a + 1]:
            break
        if df2.high[a] < df2.high[a + 2]:
            break
        if df2.high[a] < df2.high[a - 1]:
            break
        if df2.high[a] < df2.high[a - 2]:
            break
        return True
    return False

In [6]:
# two list for the fractals we found


frac1 = []
frac2 = []

# count three bars before the find the first fractal and leave space for 7 bars to the end


n1 = 3
n2 = 7

# looking through 1000 bars
e = 1000

In [7]:
# loop to add the fractals to the frac1 list
# for the row in the range of 3-7
# if row is less that 1000-7
# add the row number, the high price of the bar, and the time of the bar


for row in range(n1, e + n1):
    if uptrend(df, row, e):
        if row < e - n2:
            frac1.append((row, df.high[row], df.time[row]))

# for loop to add elements to the second list that are lower than the first fractal
for row in range(n1, e + n1):
    if uptrend2(df, row, e):
        if row < e - n2:
            frac2.append((row, df.high[row], df.time[row]))
print("The fractals for 2 are the first time are", len(frac2))
print(frac2)
# a for loop to see if any high from a candle breaks the trend line
# if it does then remove that fractal from the list and calculate the next one

The fractals for 2 are the first time are 99
[(9, 1.13574, Timestamp('2022-01-20 15:00:00')), (22, 1.13345, Timestamp('2022-01-21 04:00:00')), (29, 1.1345, Timestamp('2022-01-21 11:00:00')), (34, 1.13594, Timestamp('2022-01-21 16:00:00')), (53, 1.13357, Timestamp('2022-01-24 11:00:00')), (62, 1.13345, Timestamp('2022-01-24 20:00:00')), (75, 1.13151, Timestamp('2022-01-25 09:00:00')), (88, 1.13066, Timestamp('2022-01-25 22:00:00')), (94, 1.13103, Timestamp('2022-01-26 04:00:00')), (106, 1.1296, Timestamp('2022-01-26 16:00:00')), (111, 1.13008, Timestamp('2022-01-26 21:00:00')), (116, 1.12428, Timestamp('2022-01-27 02:00:00')), (136, 1.11489, Timestamp('2022-01-27 22:00:00')), (143, 1.11554, Timestamp('2022-01-28 05:00:00')), (150, 1.11433, Timestamp('2022-01-28 12:00:00')), (154, 1.11731, Timestamp('2022-01-28 16:00:00')), (172, 1.11819, Timestamp('2022-01-31 10:00:00')), (183, 1.12473, Timestamp('2022-01-31 21:00:00')), (196, 1.1269, Timestamp('2022-02-01 10:00:00')), (199, 1.12784, Timestamp('2022-02-01 13:00:00')), (202, 1.1274, Timestamp('2022-02-01 16:00:00')), (209, 1.12733, Timestamp('2022-02-01 23:00:00')), (214, 1.12779, Timestamp('2022-02-02 04:00:00')), (225, 1.13296, Timestamp('2022-02-02 15:00:00')), (230, 1.1314, Timestamp('2022-02-02 20:00:00')), (239, 1.1307800000000001, Timestamp('2022-02-03 05:00:00')), (244, 1.13022, Timestamp('2022-02-03 10:00:00')), (404, 1.13679, Timestamp('2022-02-14 02:00:00')), (409, 1.13512, Timestamp('2022-02-14 07:00:00')), (416, 1.1337, Timestamp('2022-02-14 14:00:00')), (422, 1.1313, Timestamp('2022-02-14 20:00:00')), (425, 1.13075, Timestamp('2022-02-14 23:00:00')), (430, 1.13221, Timestamp('2022-02-15 04:00:00')), (438, 1.13534, Timestamp('2022-02-15 12:00:00')), (441, 1.13596, Timestamp('2022-02-15 15:00:00')), (444, 1.13679, Timestamp('2022-02-15 18:00:00')), (519, 1.13353, Timestamp('2022-02-18 21:00:00')), (527, 1.13675, Timestamp('2022-02-21 05:00:00')), (541, 1.13489, Timestamp('2022-02-21 19:00:00')), (548, 1.13193, Timestamp('2022-02-22 02:00:00')), (558, 1.13665, Timestamp('2022-02-22 12:00:00')), (564, 1.13537, Timestamp('2022-02-22 18:00:00')), (574, 1.13384, Timestamp('2022-02-23 04:00:00')), (581, 1.13585, Timestamp('2022-02-23 11:00:00')), (595, 1.13082, Timestamp('2022-02-24 01:00:00')), (604, 1.1261700000000001, Timestamp('2022-02-24 10:00:00')), (616, 1.12208, Timestamp('2022-02-24 22:00:00')), (624, 1.12282, Timestamp('2022-02-25 06:00:00')), (636, 1.12664, Timestamp('2022-02-25 18:00:00')), (641, 1.1273900000000001, Timestamp('2022-02-25 23:00:00')), (644, 1.11939, Timestamp('2022-02-28 02:00:00')), (651, 1.11995, Timestamp('2022-02-28 09:00:00')), (654, 1.12315, Timestamp('2022-02-28 12:00:00')), (660, 1.12461, Timestamp('2022-02-28 18:00:00')), (676, 1.12326, Timestamp('2022-03-01 10:00:00')), (689, 1.11375, Timestamp('2022-03-01 23:00:00')), (693, 1.11351, Timestamp('2022-03-02 03:00:00')), (704, 1.11189, Timestamp('2022-03-02 14:00:00')), (708, 1.11433, Timestamp('2022-03-02 18:00:00')), (711, 1.11338, Timestamp('2022-03-02 21:00:00')), (719, 1.11063, Timestamp('2022-03-03 05:00:00')), (722, 1.11058, Timestamp('2022-03-03 08:00:00')), (728, 1.10965, Timestamp('2022-03-03 14:00:00')), (739, 1.10675, Timestamp('2022-03-04 01:00:00')), (745, 1.10388, Timestamp('2022-03-04 07:00:00')), (749, 1.10238, Timestamp('2022-03-04 11:00:00')), (761, 1.09403, Timestamp('2022-03-04 23:00:00')), (771, 1.08976, Timestamp('2022-03-07 09:00:00')), (778, 1.0932, Timestamp('2022-03-07 16:00:00')), (782, 1.08999, Timestamp('2022-03-07 20:00:00')), (790, 1.08845, Timestamp('2022-03-08 04:00:00')), (796, 1.09214, Timestamp('2022-03-08 10:00:00')), (802, 1.0924, Timestamp('2022-03-08 16:00:00')), (806, 1.09577, Timestamp('2022-03-08 20:00:00')), (814, 1.09198, Timestamp('2022-03-09 04:00:00')), (817, 1.09292, Timestamp('2022-03-09 07:00:00')), (822, 1.09921, Timestamp('2022-03-09 12:00:00')), (829, 1.10948, Timestamp('2022-03-09 19:00:00')), (845, 1.10796, Timestamp('2022-03-10 11:00:00')), (848, 1.11209, Timestamp('2022-03-10 14:00:00')), (860, 1.10185, Timestamp('2022-03-11 02:00:00')), (864, 1.101, Timestamp('2022-03-11 06:00:00')), (867, 1.10084, Timestamp('2022-03-11 09:00:00')), (871, 1.10391, Timestamp('2022-03-11 13:00:00')), (884, 1.09386, Timestamp('2022-03-14 02:00:00')), (894, 1.09893, Timestamp('2022-03-14 12:00:00')), (901, 1.09934, Timestamp('2022-03-14 19:00:00')), (913, 1.09848, Timestamp('2022-03-15 07:00:00')), (916, 1.10194, Timestamp('2022-03-15 10:00:00')), (932, 1.09735, Timestamp('2022-03-16 02:00:00')), (935, 1.09768, Timestamp('2022-03-16 05:00:00')), (944, 1.10243, Timestamp('2022-03-16 14:00:00')), (947, 1.10397, Timestamp('2022-03-16 17:00:00')), (953, 1.10464, Timestamp('2022-03-16 23:00:00')), (957, 1.10519, Timestamp('2022-03-17 03:00:00')), (965, 1.1066799999999999, Timestamp('2022-03-17 11:00:00')), (974, 1.11372, Timestamp('2022-03-17 20:00:00')), (981, 1.11181, Timestamp('2022-03-18 03:00:00')), (987, 1.10939, Timestamp('2022-03-18 09:00:00'))]

In [8]:
# for loop from the first frac to the second frac

downSlope = []
a = 0
b = 0
c = 0
while c < len(frac2):
    for bar in range(frac1[0][a], frac2[c][0]):

        # df1 = pd.DataFrame(bar)
        # The slope of the first frac[high] - frac2[high] / frac[bar] - frac2[bar]- sec frac[bar]
        barCount = frac2[c][0]
        price1 = frac1[0][1] - frac2[c][1]
        bar1 = frac1[0][0] - frac2[c][0]
        totalSlope1 = price1 / bar1
        price2 = df.high[bar] - frac2[c][1]
        bar2 = bar - frac2[c][0]
        totalSlope2 = price2 / bar2
        if len(frac2) == 1 and totalSlope2 < totalSlope1:
            a += 1
            break
        if totalSlope2 < totalSlope1:
            c += 1
            break
        # The slope of bar high to the second frac
        # slope2 = df.high[bar] - frac2[c][1] // abs(bar - frac2[c][0])
        # inner for loop for calculating each bar to the second frac
        # if the slope of slope2 is larger than slope one then break out the loop
        # and delete the item from the list

        if bar == barCount+1 and totalSlope2 >= totalSlope1:
            downSlope.append(frac2[c])

    c += 1